feat: 아이템 목록 API 연동 및 디자인 변경점 적용
uju-in/lime-frontend pull request #14
Opened 2024-01-29 10:43 UTC by yeeeerim

## 1. Changes

- 아이템 목록 API 연동
  - Header, SideMenu에 링크 연결, 정렬 적용
- 디자인 변경점 적용 (정렬 박스)

## 2. Screenshot

<img width="1510" alt="image" src="https://github.com/uju-in/lime-frontend/assets/58348662/5ea32967-040f-492d-861a-11fd4bf69a56">

## 3. Issues

1. 등록된 아이템이 별로 없어서 무한스크롤 구현을 미루고 있었는데, 아이템 생성 API 연동 작업이 dev에 병합되었으므로 해당 pr 먼저 올리고 작업 진행하겠습니다 ! (아이템 생성 잘 되는 것 확인했습니다 👍🏼 )

## 4. To Reviewer

@mintmin0320 

- 작업하면서 궁금했던 사항이 있는데, 하민님이 작업한 폴더 구조를 보니 constants, utils는 각 라우터별로 따로 폴더를 생성해두었고, types는 공통 영역 (app/_types)에 생성하셨던데 이유가 있는지 궁금합니다!
- react-query 사용이 처음이라 사용한 부분 위주로 코드 리뷰 해주시면 감사하겠습니다 🙇🏼  

## 5. Plans

- [ ] - 무한스크롤 구현
- [ ] - 찜목록 UI 변경점 구현

2024-01-29 12:59 UTC, mintmin0320 commented
고생하셨습니다 예림님! 
궁금한 부분은 코멘트로 남겨 두었습니다!

<hr/>

> 작업하면서 궁금했던 사항이 있는데, 하민님이 작업한 폴더 구조를 보니 constants, utils . . .

이 부분은 제가 놓친 것 같습니다 😅
앞으로는 각 라우터별로 _types 폴더를 만들어 운영하도록 하겠습니다!
현재 진행 중인 작업이 끝나면 수정해서 PR 올리겠습니다~

2024-01-29 13:00 UTC, mintmin0320 commented on src/app/(route)/items/_components/ItemList.tsx
> +      <strong>{price}원</strong>
toLocaleString() 메서드를 사용해서 천 단위로 구분하면 더 좋을 것 같습니다!

`<strong>{price.toLocaleString()}원</strong>`

2024-01-29 13:00 UTC, mintmin0320 commented on src/app/(route)/items/_components/ItemList.tsx
> +  )
useGetSearchParam 훅이 직접적으로 useItemListData 훅에 인자로 사용되고 있는데,

```
const hobby = useGetSearchParam('category') || '농구';
const { itemList, isLoading, isError } = useItemListData(
  hobby, sortOption.value,
)
```

위와 같이 사용하면 다음과 같은 이점이 있다고 생각합니다.
1. useGetSearchParam('category') || '농구'를 통해 얻는 값의 명확성
2. useGetSearchParam 훅이 쿼리 파라메터의 값을 가져오는 역할만 집중(단일 책임)

관련해서 예림님 의견도 궁금합니다!

2024-01-29 22:26 UTC, yeeeerim commented on src/app/(route)/items/_components/ItemList.tsx
> +  )
만들어두신 hook이 있는줄 모르고 `params.get(key)` 와 같이 사용했었다가, 수정했더니 이렇게 되어버렸네요 😢 
하민님 의견에 동의합니다! 수정해서 커밋 올리겠습니다 👍🏼 👍🏼

2024-01-31 04:56 UTC, yeeeerim commented
@mintmin0320

수정해서 바로 커밋 올려뒀었는데 확인 못하신 것 같아 멘션드립니다!!

2024-01-31 05:43 UTC, mintmin0320 commented
확인했습니다~! 👍
무한 스크롤 및 부가 작업이 업데이트 되면 해당 내용 위주로 다시 확인하도록 하겠습니다!

2024-02-13 16:56 UTC, yeeeerim commented
@mintmin0320 

무한스크롤 및 아이템 링크 추가 작업 해두었습니다!
확인 부탁드립니다 😄

2024-02-13 18:54 UTC, mintmin0320 commented
고생하셨습니다~ 👏👏
코멘트 수정사항만 반영되면 바로 병합하도록 하도록 하겠습니다!

2024-02-13 18:54 UTC, mintmin0320 requested changes

2024-02-13 18:54 UTC, mintmin0320 commented on src/app/_hook/api/useItemListData.ts
> +  }, [data])
👍 👍

2024-02-13 18:54 UTC, mintmin0320 commented on src/app/(route)/items/_components/SideMenu.tsx
> +                <a href={`/items?title=${title}&category=${item}`}>{item}</a>
❗
a 태그를 사용하게 되면, 페이지가 이동되면서 완전히 새로고침 되는 관계로 `<Link>` 태그로 대체가 필요해 보입니다!

<br/>

`before`
`<a href='/items?title=${title}&category=${item}'>${item}</a>`

<br/>

`after`
`<Link href={'/items?title=${title}&category=${item}'}>{item}</Link>`

<br/>

Reference
- [공식 문서 - Link](https://nextjs.org/docs/app/api-reference/components/link)
- [Next.JS "Link" vs "router.push()" vs "a" tag](https://stackoverflow.com/questions/65086108/next-js-link-vs-router-push-vs-a-tag)

2024-02-13 18:54 UTC, mintmin0320 commented on src/app/_hook/api/useItemListData.ts
> +      items: ItemType[]
💊  현재 `items`가 사용되고 있지 않는 것으로 보이는데, 사용 계획이 없다면 삭제해도 좋을 것 같습니다~

2024-02-14 12:56 UTC, yeeeerim commented
피드백 반영하여 commit 했습니다!
감사합니다 👍🏼

2024-02-14 12:56 UTC, mintmin0320 approved these changes

2024-02-14 12:57 UTC, merged